
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 27 22:22:59 CEST 2015
//----------------------------------------------------

package astCUP;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int ENDOBJECT = 11;
  public static final int DISTINTO = 35;
  public static final int POR = 42;
  public static final int TIPO = 2;
  public static final int CCIERRE = 8;
  public static final int ALLOC = 32;
  public static final int PCIERRE = 18;
  public static final int ELSIF = 43;
  public static final int CAP = 7;
  public static final int INT = 5;
  public static final int OUT = 30;
  public static final int SEPARADOR = 3;
  public static final int NUMENTERO = 54;
  public static final int REFERENCIA = 16;
  public static final int REC = 10;
  public static final int NOT = 50;
  public static final int AND = 48;
  public static final int IDENTIFICADOR = 9;
  public static final int MENORIGUAL = 25;
  public static final int IGUAL = 33;
  public static final int FUN = 12;
  public static final int IN = 57;
  public static final int OR = 37;
  public static final int OBJECT = 23;
  public static final int DIV = 44;
  public static final int IF = 36;
  public static final int ENDREC = 21;
  public static final int THIS = 19;
  public static final int ENDWHILE = 51;
  public static final int MAYORIGUAL = 31;
  public static final int PYCOMA = 4;
  public static final int EOF = 0;
  public static final int RETURN = 58;
  public static final int ASIG = 55;
  public static final int METHOD = 13;
  public static final int SUPER = 20;
  public static final int error = 1;
  public static final int COMA = 53;
  public static final int MENOS = 40;
  public static final int NULL = 52;
  public static final int MENOR = 28;
  public static final int MOD = 46;
  public static final int NUMREAL = 56;
  public static final int REAL = 6;
  public static final int MAYOR = 29;
  public static final int CASTINT = 60;
  public static final int PAP = 17;
  public static final int ENDIF = 45;
  public static final int ELSE = 38;
  public static final int PUNTO = 26;
  public static final int WHILE = 47;
  public static final int THEN = 41;
  public static final int EXTENDS = 24;
  public static final int END = 15;
  public static final int RETURNS = 14;
  public static final int CASTREAL = 59;
  public static final int POINTER = 22;
  public static final int APOSTROFE = 27;
  public static final int DO = 49;
  public static final int MAS = 39;
  public static final int FREE = 34;
}

